version: "3.7"

services:
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fundsy_dev
    
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    backend:
        build: ./backend
        command: bash -c "/wait && alembic revision --autogenerate && alembic upgrade head && uvicorn app.server.app:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
            - ./backend:/backend
        ports:
            - "8100:8000"
        environment:
            - DATABASE_URI=postgresql+psycopg2://postgres:postgres@db:5432/fundsy_dev
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - WAIT_HOSTS=db:5432
            - WAIT_HOSTS_TIMEOUT=300
            - WAIT_SLEEP_INTERVAL=30
            - WAIT_HOST_CONNECT_TIMEOUT=30
        depends_on:
            - db
            - redis
    
    frontend:
        build: ./frontend
        command: "yarn serve"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        ports:
            - "8081:8080"
        environment:
            - VUE_APP_API_URI=http://localhost:8100/api/v1
            - VUE_APP_LS_TOKEN_KEY=at
            - VUE_APP_LS_USER_KEY=usr
            - VUE_APP_LS_REFRESH_KEY=rt
        depends_on:
            - backend

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
        depends_on:
            - db