version: "3"

services:
    db:
        image: postgres:latest
        volumes:
            - fundsy:/db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fundsy_dev
    
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - fundsy:/redis
    
    backend:
        build: ./backend
        command: bash -c "uvicorn app.server.app:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
            - fundsy:/backend
        ports:
            - "8100:8000"
        env_file:
            - "./backend/.env"
        depends_on:
            - db
            - redis
    
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
        depends_on:
            - db

volumes:
    fundsy: