"""empty message

Revision ID: 003912e78e9d
Revises: 9f6962737426
Create Date: 2020-07-18 04:23:17.350295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003912e78e9d'
down_revision = '9f6962737426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
