"""empty message

Revision ID: 01b7e93593e7
Revises: 9d5fad69fcdb
Create Date: 2020-07-18 01:14:01.716649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b7e93593e7'
down_revision = '9d5fad69fcdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
