"""empty message

Revision ID: 1c20d7a25f25
Revises: 6c3084d0afcc
Create Date: 2020-07-15 14:11:06.208030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c20d7a25f25'
down_revision = '6c3084d0afcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
