"""empty message

Revision ID: 22d295658dfc
Revises: c3e293bf099e
Create Date: 2020-07-16 15:28:13.888110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d295658dfc'
down_revision = 'c3e293bf099e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appreciation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('old_amount', sa.Numeric(), nullable=False),
    sa.Column('customer_investment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_investment_id'], ['customer_investment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appreciation_log_id'), 'appreciation_log', ['id'], unique=False)
    op.add_column('customer_investment', sa.Column('appreciation', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_investment', 'appreciation')
    op.drop_index(op.f('ix_appreciation_log_id'), table_name='appreciation_log')
    op.drop_table('appreciation_log')
    # ### end Alembic commands ###
