"""empty message

Revision ID: 64ed705f069d
Revises: 958022498452
Create Date: 2020-07-14 22:32:33.181742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ed705f069d'
down_revision = '958022498452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_investment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_investment_id'), 'customer_investment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_investment_id'), table_name='customer_investment')
    op.drop_table('customer_investment')
    # ### end Alembic commands ###
