"""empty message

Revision ID: 6c3084d0afcc
Revises: ee811b504c4e
Create Date: 2020-07-15 01:35:55.342626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3084d0afcc'
down_revision = 'ee811b504c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
