"""empty message

Revision ID: 746bd1965d4a
Revises: 64ed705f069d
Create Date: 2020-07-14 23:31:00.207988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746bd1965d4a'
down_revision = '64ed705f069d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('customer_investment_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['customer_investment_id'], ['customer_investment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
