"""empty message

Revision ID: 78628ff47c4b
Revises: 22d295658dfc
Create Date: 2020-07-16 17:53:50.846717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78628ff47c4b'
down_revision = '22d295658dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appreciation_log', sa.Column('new_amount', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appreciation_log', 'new_amount')
    # ### end Alembic commands ###
