"""empty message

Revision ID: 958022498452
Revises: 312c6835d045
Create Date: 2020-07-12 04:14:28.518496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958022498452'
down_revision = '312c6835d045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('appreciation_amount', sa.Integer(), nullable=False),
    sa.Column('appreciation_duration', sa.Integer(), nullable=False),
    sa.Column('lock_period', sa.Integer(), nullable=False),
    sa.Column('withdrawal_cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_id'), 'investment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_id'), table_name='investment')
    op.drop_table('investment')
    # ### end Alembic commands ###
