"""empty message

Revision ID: 9d5fad69fcdb
Revises: 9f0220ee679f
Create Date: 2020-07-18 01:03:52.811164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5fad69fcdb'
down_revision = '9f0220ee679f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
