"""empty message

Revision ID: 9f6962737426
Revises: 01b7e93593e7
Create Date: 2020-07-18 04:21:31.599864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6962737426'
down_revision = '01b7e93593e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
