"""empty message

Revision ID: c3e293bf099e
Revises: 1c20d7a25f25
Create Date: 2020-07-15 15:30:37.538052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e293bf099e'
down_revision = '1c20d7a25f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_user_id_fkey', 'admin', type_='foreignkey')
    op.create_foreign_key(None, 'admin', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('customer_user_id_fkey', 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('customer_investment_customer_id_fkey', 'customer_investment', type_='foreignkey')
    op.drop_constraint('customer_investment_investment_id_fkey', 'customer_investment', type_='foreignkey')
    op.create_foreign_key(None, 'customer_investment', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'customer_investment', 'investment', ['investment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transaction_customer_investment_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_customer_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'customer_investment', ['customer_investment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transaction', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_customer_id_fkey', 'transaction', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key('transaction_customer_investment_id_fkey', 'transaction', 'customer_investment', ['customer_investment_id'], ['id'])
    op.drop_constraint(None, 'customer_investment', type_='foreignkey')
    op.drop_constraint(None, 'customer_investment', type_='foreignkey')
    op.create_foreign_key('customer_investment_investment_id_fkey', 'customer_investment', 'investment', ['investment_id'], ['id'])
    op.create_foreign_key('customer_investment_customer_id_fkey', 'customer_investment', 'customer', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_foreign_key('customer_user_id_fkey', 'customer', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.create_foreign_key('admin_user_id_fkey', 'admin', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
