"""empty message

Revision ID: cb4671cf29d2
Revises: 4c2766cdfea0
Create Date: 2020-07-17 22:12:40.878839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4671cf29d2'
down_revision = '4c2766cdfea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
