"""empty message

Revision ID: ee811b504c4e
Revises: 746bd1965d4a
Create Date: 2020-07-14 23:46:01.108323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee811b504c4e'
down_revision = '746bd1965d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_investment', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer_investment', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_investment', type_='foreignkey')
    op.drop_column('customer_investment', 'customer_id')
    # ### end Alembic commands ###
